Hw9 dagger
gorshmeister/ChatApp pull request #10
Opened 2022-11-09 04:25 UTC by gorshmeister

Создать компоненту с жизненным циклом (ЖЦ) всего приложения, где как синглтоны будут "жить" apiService-ы и другие "тяжелые" объекты на ваше усмотрение. 
Для каждого экрана создать Component или Subcomponent, в рамках которых будут "жить" зависимости с ЖЦ экрана (например, Subcomponent, которая будет предоставлять зависимости в ваши ViewModel-и)

2022-11-09 17:50 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/di/module/StreamModule.kt
> +        m4: StreamOnTopicClickMiddleware,
порешать импорты

2022-11-09 17:51 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/network/Network.kt
>      private val httpLoggingInterceptor: HttpLoggingInterceptor = HttpLoggingInterceptor().apply {
можно выпилить

2022-11-09 17:52 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/network/Network.kt
>      private val httpLoggingInterceptor: HttpLoggingInterceptor = HttpLoggingInterceptor().apply {
можно выпилить

2022-11-09 18:01 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/di/module/ChannelModule.kt
> +        return PagerAdapter(channelsFragment.parentFragmentManager, channelsFragment.lifecycle)
PagerAdapter лучше не через DI, а руками поставлять. Это чистая UI-ая штука, нет смысла её даггером прокидывать. Аналогично убрать DI UI-штук в других местах.

2022-11-09 18:59 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/ChannelsFragment.kt
> +    lateinit var channelComponent: ChannelComponent
Проверить что скоупы ChannelScope, ChatScope и тд правильно работают. Суть в том, что сущности, помеченные аннотацией скоупа, живут в рамках этого скоупа. Когда мы покидаем скоуп, то и эти сущности тоже умирают. Проверить можно через Profiler, путём записи памяти. Если скоуп работает не так, то погуглить как правильно его использовать.

2022-11-09 19:00 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/ChannelsFragment.kt
> +    fun initViews(pagerAdapter: PagerAdapter) {
методы дёргаем руками

2022-11-09 19:00 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/ChannelsFragment.kt
> +        channelComponent.inject(this)
инжектить тоже можно в onAttach

2022-11-09 19:02 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    lateinit var streamViewModel: MviViewModel<StreamAction, StreamState, StreamEffect>
сейчас вью-модель поставляется стандартной фабрикой даггера. Т.е. каждый раз создаётся новый инстанс, и onCleared не вызывается. Вью-модель лучше создавать через гугловский делегат by viewModels, используя ViewModelFactory для инжекта

2022-11-09 19:06 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    lateinit var streamViewModel: MviViewModel<StreamAction, StreamState, StreamEffect>
```kotlin
class ViewModelFactory<T : ViewModel> @Inject constructor(
    private val viewModel: Lazy<T>
) : ViewModelProvider.Factory {

    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        return viewModel.get() as? T ?: throw IllegalArgumentException("error view model")
    }
}
```

2022-11-09 19:12 UTC, turik2304 requested changes
Поправить:
- вью-модель
- чекнуть скоупы
- не инжектить UI-штуки
- нейминг
- code cleanup

2022-11-10 04:39 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/di/module/StreamModule.kt
> +        m4: StreamOnTopicClickMiddleware,
+

2022-11-10 05:11 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/network/Network.kt
>      private val httpLoggingInterceptor: HttpLoggingInterceptor = HttpLoggingInterceptor().apply {
+

2022-11-10 05:11 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/network/Network.kt
>      private val httpLoggingInterceptor: HttpLoggingInterceptor = HttpLoggingInterceptor().apply {
+

2022-11-10 05:12 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/di/module/ChannelModule.kt
> +        return PagerAdapter(channelsFragment.parentFragmentManager, channelsFragment.lifecycle)
+

2022-11-10 05:12 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/ChannelsFragment.kt
> +    fun initViews(pagerAdapter: PagerAdapter) {
+

2022-11-10 05:12 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/ChannelsFragment.kt
> +        channelComponent.inject(this)
+

2022-11-10 07:51 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    lateinit var streamViewModel: MviViewModel<StreamAction, StreamState, StreamEffect>
проверить

2022-11-10 18:14 UTC, turik2304 approved these changes

2022-11-10 18:15 UTC, merged