Hw6 network
gorshmeister/ChatApp pull request #5
Opened 2022-09-13 18:19 UTC by gorshmeister

"Работа с сетью"

В данном задании вам предлагается наконец-то начать работать не с моками, а с реальными данными. Вам необходимо осуществлять запросы непосредственно к [методам Zulip api](https://zulip.com/api).

Ваше приложение должно получать стримы, топики, сообщения в топиках, профили и статус пользователя(active/idle/offline) непосредственно через апи.
Также через апи нужно посылать сообщения в топики, выставлять и удалять реакции.

API key и email для авторизации пока что нужно захардкодить.
Из них вы должны получить строку Basic access authentication - в нашем случае это пара email, API key, закодированные в base64.
Чтобы получить эту строку вы можете воспользоваться методом Credentials.basic("sample@mail.ru", "api_key").
Полученную строку вам нужно подставлять в хэдер авторизации(Authorization) при каждом запросе.

Текстовый статус "In a meeting" у пользователя уберите из дизайна.
Вместо зеленого статуса online у вас будет active(зеленый)/idle(оранжевый)/offline(красный).
Кнопку Log out уберите.

Требования:
Для запросов к апи использовать Retrofit + RxJava

2022-09-13 18:49 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/network/model/GetUserResponse.kt
> +    val color: String
у сериализотра есть флаг **isLenient**, попробовать заюзать его и использовать одну модель данных для стримов

2022-09-13 19:07 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfilePresenter.kt
> +    private val compositeDisposable = CompositeDisposable()
подписки не чистятся

2022-09-13 19:07 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +    override fun setProfile(name: String, avatar: String) {
```suggestion
    override fun setProfile(name: String, avatarUrl: String) {
```

2022-09-13 19:07 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfilePresenter.kt
> +                        avatar = response.members.avatarUrl
```suggestion
                        avatarUrl = response.members.avatarUrl
```

2022-09-13 19:07 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileView.kt
> +    fun setProfile(name: String, avatar: String)
```suggestion
    fun setProfile(name: String, avatarUrl: String)
```

2022-09-13 19:19 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/utils/ItemDiffUtil.kt
> +            (oldItem is DateUi) && (newItem is DateUi) -> oldItem.text == newItem.text
учитывая тот факт, что в дифф-утил попадают классы-итемы, которые **data**, то можно просто сравнивать их тут через ==

2022-09-13 19:41 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/people/PeoplePresenter.kt
> +            "active" -> PeopleUi.PeopleStatus.ONLINE
aggregated.status можно десериализовывать сразу в **enum**

2022-09-13 20:09 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +            tvTopicName.text = "Topic: #$topicName"
использовать ресурсы. Почитать про plurals

2022-09-13 20:10 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +        var streamName: String = "stream"
перенести в презентер. Значения можно запоминать в поля при вызове метода загрузки данных

2022-09-13 20:14 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                requireActivity().window.statusBarColor =
проверить гипотезу - менять цвет статус бара в onStart на ChannelsFragment

2022-09-13 20:27 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        return Observable.just(list.toList())
здесь можно просто лист возвращать, используя **map**

2022-09-13 20:37 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +                { view.scrollMsgsToTheEnd() },
лишняя строка вроде, проверить

2022-09-13 20:47 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        api.getMessage(id = messageId, apply_markdown = true)
когда будет БД, то это сообщение лучше тянуть из базы, избегая лишнего похода в сеть

2022-09-13 21:26 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        Observable.interval(0, 5000, TimeUnit.MILLISECONDS)
Поправить цепочку по принципу на картинке. (Разобраться с _queueId_ и _lastEventId_)

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/73557404/190012186-22b6923a-f10a-43db-aea1-d3213c91de73.png">

2022-09-13 21:40 UTC, turik2304 requested changes
Основное - поправить цепочку с лонгполлингом в чате, остальное всё ок, за исключением мелких правок

2022-09-14 06:59 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfilePresenter.kt
> +    private val compositeDisposable = CompositeDisposable()
+

2022-09-14 07:04 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +    override fun setProfile(name: String, avatar: String) {
+

2022-09-14 07:04 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfilePresenter.kt
> +                        avatar = response.members.avatarUrl
+

2022-09-14 07:05 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileView.kt
> +    fun setProfile(name: String, avatar: String)
+

2022-09-14 07:11 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/utils/ItemDiffUtil.kt
> +            (oldItem is DateUi) && (newItem is DateUi) -> oldItem.text == newItem.text
+

2022-09-14 07:27 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/people/PeoplePresenter.kt
> +            "active" -> PeopleUi.PeopleStatus.ONLINE
+

2022-09-14 07:51 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +            tvTopicName.text = "Topic: #$topicName"
+

2022-09-14 08:07 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +        var streamName: String = "stream"
+

2022-09-14 08:14 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        return Observable.just(list.toList())
+

2022-09-14 08:15 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +                { view.scrollMsgsToTheEnd() },
+

2022-09-14 10:49 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/network/model/GetUserResponse.kt
> +    val color: String
+

2022-09-14 10:54 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                requireActivity().window.statusBarColor =
Не получилось

2022-09-14 11:07 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        api.getMessage(id = messageId, apply_markdown = true)
+

2022-09-20 17:37 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                requireActivity().window.statusBarColor =
переопределить onBackPressed
https://proandroiddev.com/backpress-handling-in-android-fragments-the-old-and-the-new-method-c41d775fb776

2022-09-20 17:56 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                    if (areTheMessagesUploaded) {
флаг загрузки перенести в презентер

2022-09-20 17:57 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatView.kt
> +    fun uploadMoreMessages()
лишний метод интерфейса, тк к презентеру идёт прямое обращение - presenter.someMethod()

2022-09-20 17:57 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +            .map { messages -> (displayedItems + messages).toSet() }
```suggestion
            .map { messages -> (displayedItems + messages).distinctBy { it.id } }
```

2022-09-20 18:01 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +            val layoutManager = LinearLayoutManager(requireContext())
layoutManager можно вытащить из ресайклера

2022-09-20 18:02 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +            val layoutManager = LinearLayoutManager(requireContext())
val layoutManager = rvItems.layoutManager as? LinearLayoutManager

2022-09-20 18:07 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        msgDisposable.dispose()
lateinit лучше проверять через this::msgDisposable.isInitialized

2022-09-20 18:22 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +        presenter.registerReactionQueue()
регистрировать очереди лучше после загрузки сообщений

2022-09-20 18:23 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +        presenter.registerReactionQueue()
и надо бы вынести регистрацию в презентер

2022-09-20 18:54 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                        if (layoutManager.findLastVisibleItemPosition() == adapter.items.size - 1) {
поправить условие, использовать findFirst...

2022-09-20 18:54 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                        if (layoutManager.findLastVisibleItemPosition() == adapter.items.size - 1) {
+dy

2022-09-20 18:55 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        return messages.map { item ->
вернуть запрос сообщений, тк получается дикая дичь

2022-09-20 18:57 UTC, turik2304 requested changes
поправить мелочь

2022-09-21 04:37 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                requireActivity().window.statusBarColor =
+

2022-09-21 04:39 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatView.kt
> +    fun uploadMoreMessages()
+

2022-09-21 04:57 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +            val layoutManager = LinearLayoutManager(requireContext())
+

2022-09-21 05:03 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        msgDisposable.dispose()
+

2022-09-21 05:03 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +        presenter.registerReactionQueue()
+

2022-09-21 05:03 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                        if (layoutManager.findLastVisibleItemPosition() == adapter.items.size - 1) {
+

2022-09-21 05:12 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                    if (areTheMessagesUploaded) {
+

2022-09-21 05:24 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +            .map { messages -> (displayedItems + messages).toSet() }
+

2022-09-21 10:11 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                requireActivity().window.statusBarColor =
проверить

2022-09-21 10:11 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                    if (areTheMessagesUploaded) {
+

2022-09-21 10:11 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatView.kt
> +    fun uploadMoreMessages()
+

2022-09-21 10:11 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +            .map { messages -> (displayedItems + messages).toSet() }
+

2022-09-21 10:12 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +            val layoutManager = LinearLayoutManager(requireContext())
+

2022-09-22 06:19 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        return messages.map { item ->
+

2022-09-30 16:58 UTC, turik2304 approved these changes

2022-09-30 16:59 UTC, merged