hw7
gorshmeister/ChatApp pull request #6
Opened 2022-09-30 07:40 UTC by gorshmeister

"Хранение данных"

**1. Кешировать списки стримов, топиков и сообщений**
- Теперь если у нас есть какие-то данные в кешах, то мы сперва показываем их (вместо шиммера), 
  а после получения данных из сети показываем актуальные данные
- Если БД пустая по конкретным топикам, то показываем шиммер  

**2. Реализовать пагинацию при подгрузке сообщений**
- Подгружать только по 20 сообщений за раз
- Начинать загрузку следующей страницы необходимо как только пользователь доскроллил до n-5 позиции, где n - это размер списка вообщений в адаптере
- В базе данных хранить последних 50 сообщений и показывать их при старте приложения до тех пор пока не подгрузятся новые сообщения из сети

**3. Доп задание (не обязательно): реализовать отправку вложений и их получение

2022-09-30 16:46 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                    }
вынести повторяющийся код в один метод

2022-09-30 16:48 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                        } catch (e:UninitializedPropertyAccessException) {
проверить актуальность исключения

2022-09-30 17:05 UTC, turik2304 commented on app/build.gradle
> +    annotationProcessor 'androidx.room:room-compiler:2.4.3'
можно удалить

2022-09-30 17:22 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/AppDataBase.kt
> +                    "appDataBase",
вынести в константу

2022-09-30 17:36 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/MessageWithReactions.kt
> +    var reactions : List<ReactionEntity> = ArrayList()
избавиться от nullable var, добавить data

2022-09-30 17:57 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/MessageDao.kt
> +    fun deleteMessage(messageId: Int): Single<Unit>
поправить Single<Unit> в Completable

2022-09-30 17:59 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/StreamWithTopics.kt
> +class StreamWithTopics {
сделать аналогично с MessageWithReactions

2022-09-30 17:59 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/StreamDao.kt
> +    fun insert(topics: List<TopicEntity>): Single<Unit>
Single в Completable

2022-09-30 18:16 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/repositories/StreamRepository.kt
> +    private val api: ZulipApi = Network.api
api тоже можно в конструктор

2022-09-30 20:17 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    private val db: AppDataBase by lazy { AppDataBase.getDataBase(requireContext()) }
создать Application, перенести в презентер

2022-09-30 20:17 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    private val streamRepository: StreamRepository by lazy { StreamRepository(db.streamDao()) }
перенести в презентер

2022-09-30 20:28 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/repositories/ChatRepository.kt
> +class ChatRepository(private val messageDao: MessageDao) {
В ДОМАШКЕ ПО АРХИТЕКТУРЕ:
поправить репозиторий, пример в ветке ...repo_with_db_example

2022-09-30 20:29 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/data/repositories/StreamRepository.kt
> +class StreamRepository(private val streamDao: StreamDao) {
В ДОМАШКЕ ПО АРХИТЕКТУРЕ:
поправить репозиторий, пример в ветке ...repo_with_db_example

2022-09-30 20:30 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +    private val db: AppDataBase by lazy { AppDataBase.getDataBase(requireContext()) }
перенести в презентер

2022-09-30 20:33 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +        presenter.loadMessagesFromApi()
В ДОМАШКЕ ПО АРХИТЕКТУРЕ:
должен быть один метод presenter.loadMessages(...)

2022-09-30 20:35 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        api.getMessage(id = messageId, applyMarkdown = true)
В ДОМАШКЕ ПО АРХИТЕКТУРЕ:
презентер не должен напрямую ходить в апи, сделать через презентер

2022-09-30 20:37 UTC, turik2304 commented on build.gradle
> +ext {
лишнее

2022-09-30 20:51 UTC, turik2304 requested changes
1. Поправить то что не помечено в этой ветке 
2. Помеченные комменты поправить в 8ой ветке - отдельный ПР
3. После всех правок приступить к изучению и реализации Clean Architecture + MVI/MVP - отдельный ПР

2022-10-03 04:08 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                    }
+

2022-10-03 04:21 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +                        } catch (e:UninitializedPropertyAccessException) {
+

2022-10-03 04:24 UTC, gorshmeister commented on app/build.gradle
> +    annotationProcessor 'androidx.room:room-compiler:2.4.3'
+

2022-10-03 04:31 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/AppDataBase.kt
> +                    "appDataBase",
+

2022-10-03 04:45 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/MessageWithReactions.kt
> +    var reactions : List<ReactionEntity> = ArrayList()
+

2022-10-03 04:46 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/MessageDao.kt
> +    fun deleteMessage(messageId: Int): Single<Unit>
+

2022-10-03 04:58 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/StreamWithTopics.kt
> +class StreamWithTopics {
+

2022-10-03 04:58 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/database/dao/StreamDao.kt
> +    fun insert(topics: List<TopicEntity>): Single<Unit>
+

2022-10-03 05:01 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/repositories/StreamRepository.kt
> +    private val api: ZulipApi = Network.api
+

2022-10-03 05:30 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    private val db: AppDataBase by lazy { AppDataBase.getDataBase(requireContext()) }
+

2022-10-03 05:31 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    private val streamRepository: StreamRepository by lazy { StreamRepository(db.streamDao()) }
+

2022-10-03 05:31 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +    private val db: AppDataBase by lazy { AppDataBase.getDataBase(requireContext()) }
+

2022-10-03 05:31 UTC, gorshmeister commented on build.gradle
> +ext {
+

2022-10-03 05:33 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/channels/StreamFragment.kt
> +    private val streamRepository: StreamRepository by lazy { StreamRepository(db.streamDao()) }
+

2022-10-04 06:48 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatPresenter.kt
> +        api.getMessage(id = messageId, applyMarkdown = true)
+

2022-10-04 06:49 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/repositories/StreamRepository.kt
> +class StreamRepository(private val streamDao: StreamDao) {
+

2022-10-04 06:49 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/data/repositories/ChatRepository.kt
> +class ChatRepository(private val messageDao: MessageDao) {
+

2022-10-04 12:05 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/chat/ChatFragment.kt
> +        presenter.loadMessagesFromApi()
+

2022-10-05 16:08 UTC, turik2304 approved these changes

2022-10-05 16:08 UTC, merged