hw8.1: trying MVI
gorshmeister/ChatApp pull request #8
Opened 2022-10-25 07:52 UTC by gorshmeister

2022-10-25 15:48 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/di/GlobalDI.kt
> +    val profileStore = (Store(
перенести создание инстанса во фрагмент

2022-10-25 17:11 UTC, turik2304 requested changes
доделать:
- разнести сущности
- закрыть абстракциями
- конкретизировать стейты

2022-10-26 04:03 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/di/GlobalDI.kt
> +    val profileStore = (Store(
+

2022-10-26 17:58 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileAction.kt
> +    class ProfileFailureAction(val error: Throwable) : ProfileInternalAction()
нейминг можно покороче

2022-10-26 18:04 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileState.kt
> +    val error: Throwable? = null,
разбить на конкретные кусочки, используя sealed class

2022-10-26 18:28 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/mvi_core/Reducer.kt
> +}
обработать эффекты:

interface Reducer<S, A, E> {
    fun reduceToState(state: S, action: A): S
    fun reduceToEffect(state: S, action: A): E?
}

2022-10-26 18:29 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/mvi_core/Store.kt
> +            .subscribe(state::accept)
обработать эффекты также

2022-10-26 18:29 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +        val uiEffect = PublishRelay.create<UiEffects>()
избавиться от PublishRelay в статике

2022-10-26 18:29 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +            initialState = ProfileState(isLoading = false, data = null, error = null)
initialState - стейт который будет отрисован в первую очередь, скорее всего тут подойдет Loading

2022-10-26 18:42 UTC, turik2304 commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +    private val _actions = PublishRelay.create<ProfileAction>()
Прокидывать action в стор напрямую:
- завести метод accept/dispatch в MviViewModel
- завести метод accept/dispatch в Store
- кидать экшены из этого метода во внутренний PublishSubject<Action>

2022-10-26 18:49 UTC, turik2304 requested changes
Поправить:
- эффекты
- экшены
- стейты
- нейминг

2022-10-27 04:39 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileAction.kt
> +    class ProfileFailureAction(val error: Throwable) : ProfileInternalAction()
+

2022-10-27 04:54 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileState.kt
> +    val error: Throwable? = null,
+

2022-10-27 04:56 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +            initialState = ProfileState(isLoading = false, data = null, error = null)
+

2022-10-27 05:17 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +    private val _actions = PublishRelay.create<ProfileAction>()
+

2022-10-27 05:46 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/mvi_core/Reducer.kt
> +}
+

2022-10-27 05:46 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/mvi_core/Store.kt
> +            .subscribe(state::accept)
+

2022-10-27 05:46 UTC, gorshmeister commented on app/src/main/java/ru/gorshenev/themesstyles/presentation/ui/profile/ProfileFragment.kt
> +        val uiEffect = PublishRelay.create<UiEffects>()
+

2022-10-27 17:46 UTC, turik2304 approved these changes

2022-10-27 17:47 UTC, merged